translate install-the-hard-way guide to Chinese (#12)
clusternet/website pull request #40
Opened 2022-09-08 06:12 UTC by JaneConan

Signed-off-by: ConanYao <JaneConan@live.com>

What type of PR is this?
translate install-the-hard-way guide to Chinese

Implement https://github.com/clusternet/website/issues/12

2022-09-08 08:08 UTC, dixudx commented on content/zh-cn/docs/installation/install-the-hard-way.md
> +接下来，您需要为群集注册创建一个令牌，这将用于
s/令牌/token，专有名词可以不翻译

2022-09-08 08:08 UTC, dixudx commented on content/zh-cn/docs/installation/install-the-hard-way.md
> +`clusternet-agent` 可以配置以下三种 `SyncMode` （通过标志 `--cluster-sync-mode`配置）,
s/标志/参数

2022-09-08 08:23 UTC, yiwei-C requested changes

2022-09-08 08:23 UTC, yiwei-C commented on content/zh-cn/docs/installation/install-the-hard-way.md
> +您需要在子集群中部署“clusternet-agent”，在父集群中部署“clusternet-hub”和“clusternet-scheduler”。
这些组件名称，请把“”改成``

2022-09-08 08:23 UTC, yiwei-C commented on content/zh-cn/docs/installation/install-the-hard-way.md
> +您可以选择要使用的最快镜像地址。
您可自由选择，从更方便的镜像地址下载

2022-09-08 08:23 UTC, yiwei-C commented on content/zh-cn/docs/installation/install-the-hard-way.md
> +## 检查集群注册
检查集群注册状态

2022-09-08 08:23 UTC, yiwei-C commented on content/zh-cn/docs/installation/install-the-hard-way.md
> +# 在部署之前，如果需要，您可以更新同步模式(SyncMode)
如果需要选用其他同步模式，请修改以下 YAML 文件中的 `SyncMode`

2022-09-08 08:23 UTC, yiwei-C commented on content/zh-cn/docs/installation/install-the-hard-way.md
> +上面的 `PARENTURL` 是您要注册到的父集群的 apiserver 地址， 即 `https` 方案必须指定，它是目前唯一支持的。 如果 apiserver 服务器未侦听标准 https 端口 (:443), 请在 URL 中指定端口号，以确保代理连接到正确的端点，对于实例 `https://192.168.10.10:6443`。
`apiserver`地址必须以`https`开头。目前仅支持`https`

2022-09-08 08:23 UTC, yiwei-C commented on content/zh-cn/docs/installation/install-the-hard-way.md
> +> 如果您要使用上面创建服务帐户令牌，请将上面的 `07401b.f395accd246ae52d` 替换为上面的长字符串输出的令牌。
如果您是通过`service account token`验证，请将`07401b.f395accd246ae52d`替换为之前生成的token

2022-09-08 09:45 UTC, dixudx reviewed
Thanks for your contribution. We're getting close.

2022-09-08 09:45 UTC, dixudx commented on content/zh-cn/docs/installation/install-the-hard-way.md
> +本教程将引导您以“最硬核”的方式安装 Clusternet。 您也可以尝试参考 [使用Helm安装'Clusternet'](/docs/getting-started/install-with-helm)进行安装。
这里链接到中文的文档吧，`/zh-cn/docs/installation/install-with-helm/`

2022-09-08 09:45 UTC, dixudx commented on content/zh-cn/docs/installation/install-the-hard-way.md
> +“最硬核”的方式安装 Clusternet 针对安装过程进行了优化，您可以一步一步的来了解 Clusternet，以确保您能理解每个必要的步骤，以便于确保成功安装 `Clusternet`。
这种“最硬核”的方式便于您学习，并理解安装 Clusternet 所需要的每一个任务。

2022-09-08 09:45 UTC, dixudx commented on content/zh-cn/docs/installation/install-the-hard-way.md
> +接下来，您需要为群集注册创建一个 token。这将用于
随后会被 `clusternet-agent` 使用到。

2022-09-08 09:45 UTC, dixudx commented on content/zh-cn/docs/installation/install-the-hard-way.md
> +- 如果支持`bootstrapping`身份验证，即配置 `--enable-bootstrap-token-auth=true` `kube-apiserver` 将在父集群中运行，
即在父集群中运行的`kube-apiserver`显式地设置了`--enable-bootstrap-token-auth=true`

2022-09-08 09:45 UTC, dixudx commented on content/zh-cn/docs/installation/install-the-hard-way.md
> +特性功能  `AppPusher`  在代理端工作，主要出于以下两个原因引入，
在 agent 侧工作

2022-09-08 09:45 UTC, dixudx commented on content/zh-cn/docs/installation/install-the-hard-way.md
> +部署 `clusternet-agent`后，应首先创建包含群集注册token的机密。
在部署`clusternet-agent`的时候，应提前创建一个secret 对象，包含着可用于集群注册的 token。

2022-09-09 01:58 UTC, dixudx approved these changes
Thanks for your contribution. Good work.

2022-09-09 01:59 UTC, merged